//package com.hoi4utils.script2
//
//import com.hoi4utils.script.scripter.DefaultNodeScripter
//
//import java.io.{File, FileNotFoundException, PrintWriter}
//import java.time.LocalDateTime
//import javax.swing.JOptionPane
//import scala.util.Using
//
//trait PDXFile extends PDXScript[?] {
//  
//  def getFile: Option[File]
//
//  def fileName: String = getFile match
//    case Some(file) => file.getName
//    case None => getClass.getSimpleName + ".txt"
//
//  def fileNameOrElse(defaultName: String): String = getFile match
//    case Some(file) => file.getName
//    case None => defaultName
//
//  def save(): Unit = this.getFile match
//    case Some(file) =>
//      Using(new PrintWriter(file)) { writer =>
//        writer.println(s"### Generated by HOI4Utils, time: ${LocalDateTime.now} ###")
//        writer.println(this.toScript)
//        logger.info("Exported PDXScript {} to {}", this, file)
//      } recover {
//        case e: FileNotFoundException =>
//          logger.error("Error exporting PDXScript: {}", e.getMessage)
//          JOptionPane.showMessageDialog(null, "Error exporting PDXScript: " + e.getMessage, "Error", JOptionPane.ERROR_MESSAGE)
//      }
//    case None =>
//      logger.error("Error exporting PDXScript: No file found for {}", this)
//      JOptionPane.showMessageDialog(null, s"Error exporting PDXScript: No file found for $this", "Error", JOptionPane.ERROR_MESSAGE)
//
//}
