package clausewitz_coding.code.modifier;

public class NavalModifier implements Modifier {
	public NavalModifier() {

//		super(Scope.naval);
	}

	@Override
	public Scope getScope() {
		return Scope.naval;
	}

	public enum modifiers {
		amphibious_invasion,
		amphibious_invasion_defence,
		assign_navy_leader_cp_cost,
		carrier_capacity_penalty_reduction,
		carrier_traffic,
		convoy_escort_efficiency,
		convoy_raiding_efficiency_factor,
		convoy_retreat_speed,
		critical_receive_chance,
		experience_gain_navy,
		experience_gain_navy_factor,
		experience_gain_navy_unit,
		experience_gain_navy_unit_factor,
		female_random_admiral_chance,
		fighter_sortie_efficiency,
		invasion_preparation,
		mines_planting_by_fleets_factor,
		mines_sweeping_by_fleets_factor,
		naval_accidents_chance,
		naval_attrition,
		naval_coordination,
		naval_critical_effect_factor,
		naval_critical_score_chance_factor,
		naval_damage_factor,
		naval_defense_factor,
		naval_detection,
		naval_enemy_fleet_size_ratio_penalty_factor,
		naval_enemy_positioning_in_initial_attack,
		naval_enemy_retreat_chance,
		naval_has_potf_in_combat_attack,
		naval_has_potf_in_combat_defense,
		naval_hit_chance,
		naval_invasion_capacity,
		naval_invasion_penalty,
		naval_mine_hit_chance,
		naval_mines_damage_factor,
		naval_mines_effect_reduction,
		naval_morale,
		naval_morale_factor,
		naval_night_attack,
		naval_retreat_chance,
		naval_retreat_chance_after_initial_combat,
		naval_retreat_speed,
		naval_retreat_speed_after_initial_combat,
		naval_speed_factor,
		naval_strike,
		naval_torpedo_cooldown_factor,
		naval_torpedo_hit_chance_factor,
		naval_torpedo_reveal_chance_factor,
		naval_torpedo_screen_penetration_factor,
		navy_advisor_cost_factor,
		navy_anti_air_attack,
		navy_anti_air_attack_factor,
		navy_capital_ship_attack_factor,
		navy_capital_ship_defence_factor,
		navy_carrier_air_agility_factor,
		navy_carrier_air_attack_factor,
		navy_carrier_air_targetting_factor,
		navy_casualty_on_hit,
		navy_casualty_on_sink,
		navy_fuel_consumption_factor,
		navy_max_range,
		navy_max_range_factor,
		navy_org,
		navy_org_factor,
		navy_screen_attack_factor,
		navy_screen_defence_factor,
		navy_submarine_attack_factor,
		navy_submarine_defence_factor,
		navy_submarine_detection_factor,
		navy_visibility,
		night_spotting_chance,
		port_strike,
		positioning,
		repair_speed_factor,
		screening_efficiency,
		screening_without_screens,
		ships_at_battle_start,
		sortie_efficiency,
		spotting_chance,
		strike_force_movement_org_loss,
		sub_retreat_speed,
		submarine_attack,
		terrain_trait_xp_gain_factor,
		transport_capacity,
	}
}
