package com.hoi4utils.ui.localization

import com.hoi4utils.hoi4.common.national_focus.{Focus, FocusTree, FocusTreeManager}
import com.hoi4utils.hoi4.common.national_focus.FocusTreeManager.focusTreeErrors
import com.hoi4utils.hoi4.localization.service.LocalizationService
import com.hoi4utils.hoi4.localization.{Localization, Property}
import com.hoi4utils.main.{HOIIVUtils, HOIIVUtilsConfig}
import com.hoi4utils.ui.javafx.application.HOIIVUtilsAbstractController2
import com.hoi4utils.ui.javafx.scene.layout.ErrorIconPane
import javafx.collections.{FXCollections, ObservableList}
import javafx.fxml.FXML
import javafx.scene.control.cell.TextFieldTableCell
import javafx.scene.control.{Button, CheckBox, Label, ProgressIndicator, RadioMenuItem, TableColumn, TableRow, TableView, ToggleButton, ToggleGroup, ToolBar}
import javafx.scene.layout.{AnchorPane, HBox, VBox}
import javafx.scene.paint.Color
import scalafx.geometry.Insets
import zio.ZIO

import scala.collection.mutable.ListBuffer
import scala.compiletime.uninitialized

class FocusTreeLocalization2Controller extends HOIIVUtilsAbstractController2:

  @FXML private var ftlRoot: AnchorPane = uninitialized
  @FXML private var toolBar: ToolBar = uninitialized
  @FXML private var toolBar2: ToolBar = uninitialized
  @FXML private var versionLabel: Label = uninitialized
  @FXML private var saveButton: Button = uninitialized
  @FXML private var toggleGroup: ToggleGroup = uninitialized
  @FXML private var focusTreesCount: Label = uninitialized
  @FXML private var vbox: VBox = uninitialized
  @FXML private var welcome: ToggleButton = uninitialized
  @FXML private var progressIndicator: ProgressIndicator = uninitialized
  @FXML private var focusListTable: TableView[Focus] = uninitialized
  @FXML private var focusIDColumn: TableColumn[Focus, String] = uninitialized
  @FXML private var focusNameColumn: TableColumn[Focus, String] = uninitialized
  @FXML private var focusDescColumn: TableColumn[Focus, String] = uninitialized
  @FXML private var focusLocStatusColumn: TableColumn[Focus, String] = uninitialized
  @FXML private var localizationStatusItem: CheckBox = uninitialized
  @FXML private var autoGenerateDescItem: CheckBox = uninitialized

  private var generateDummyDescriptions = false
  private var focusTreesToggleButtons: ListBuffer[ToggleButton] = ListBuffer.empty

  setFxmlFile("FocusTreeLocalization2.fxml")
  setTitle("Focus Tree Localization 2")

  @FXML def initialize(): Unit =
    setWindowControlsVisibility()
    versionLabel.setText(s"Version: ${HOIIVUtilsConfig.get("version")}")
    welcome.setToggleGroup(toggleGroup)
    welcome.fire()
    populateFocusTreeSelection()

  override def preSetup(): Unit = setupWindowControls(ftlRoot, toolBar, toolBar2)

  @FXML def handleWelcome(): Unit =
    welcome.setSelected(true)
    focusTreesToggleButtons.foreach(btn =>
      btn.setSelected(false)
    )
//    clearFocusTreeView()
//    setCC()
//    setRC()
//    focusTreeView.add(Label(welcomeMessage), 0, 0)
//    focusTreeView.setGridLinesVisible(lines)
//    if focusDetailsPaneController != null then
//      focusDetailsPaneController.clear()

  @FXML def handleShowFocusLocalizationSettingAction(): Unit = focusLocStatusColumn.setVisible(localizationStatusItem.isSelected)

  @FXML def handleToggleAutoGenerateDescription(): Unit = generateDummyDescriptions = autoGenerateDescItem.isSelected

  private def populateFocusTreeSelection(): Unit =
    Some(FocusTreeManager.observeFocusTrees.sorted()).foreach(trees =>
      trees.forEach(someFocusTree =>
        val toggleButton = ToggleButton(someFocusTree.toString)
        focusTreesToggleButtons += toggleButton
        toggleButton.setToggleGroup(toggleGroup)
        toggleButton.setOnAction(_ => {
          if toggleButton.isSelected then
            // Manually deselect all other buttons
            focusTreesToggleButtons.foreach(btn =>
              if btn != toggleButton then
                btn.setSelected(false)
                welcome.setSelected(false)
            )
            welcome.setSelected(false)
            loadFocusTree(someFocusTree)
          else
            toggleButton.setSelected(false)
            toggleButton.setSelected(true)
            loadFocusTree(someFocusTree)
        })
        toggleButton.setPadding(Insets(5, 10, 5, 10))
        // Check if this focus tree has errors
        val hasErrors = focusTreeErrors.exists(_.focusTreeId == someFocusTree.id.str)
        if hasErrors then
          // Create HBox to hold toggle button and error icon
          val hbox = new HBox(5)
          hbox.setAlignment(javafx.geometry.Pos.CENTER_LEFT)
          hbox.getChildren.add(toggleButton)
          // Get the error count for this focus tree
          val errorCount = focusTreeErrors
            .find(_.focusTreeId == someFocusTree.id.str)
            .map(_.focusErrors.map(_.errors.size).sum)
            .getOrElse(0)
          // Create error icon pane
          val errorIcon = new ErrorIconPane(
            iconSize = 24,
            errorNumberCount = errorCount,
            onDoubleClick = Some(() => {
              // TODO: Open error details dialog or navigate to error list
              logger.info(s"Double-clicked error icon for ${someFocusTree.id.str}")
            }),
            tooltipText = Some(s"$errorCount error(s) in this focus tree")
          )
          errorIcon.build()
          hbox.getChildren.add(errorIcon)
          vbox.getChildren.add(hbox)
        else
          vbox.getChildren.add(toggleButton)
      )
      focusTreesCount.setText(s"Focus Trees: ${trees.size()}")
    )
    FocusTreeManager.sharedFocusFilesAsPseudoTrees.foreach(pseudoTree =>
      val toggleButton = ToggleButton(pseudoTree.toString)
      focusTreesToggleButtons += toggleButton
      toggleButton.setToggleGroup(toggleGroup)
      toggleButton.setOnAction(_ => {
        if toggleButton.isSelected then
          // Manually deselect all other buttons
          focusTreesToggleButtons.foreach(btn =>
            if btn != toggleButton then
              btn.setSelected(false)
              welcome.setSelected(false)
          )
          welcome.setSelected(false)
          loadFocusTree(pseudoTree)
        else
          toggleButton.setSelected(false)
          toggleButton.setSelected(true)
          loadFocusTree(pseudoTree)
      })
      toggleButton.setPadding(Insets(5, 10, 5, 10))
      // Check if this shared focus tree has errors
      val hasErrors = focusTreeErrors.exists(_.focusTreeId == s"[Shared Focuses] ${pseudoTree.id.str}")
      if hasErrors then
        // Create HBox to hold toggle button and error icon
        val hbox = new HBox(5)
        hbox.setAlignment(javafx.geometry.Pos.CENTER_LEFT)
        hbox.getChildren.add(toggleButton)
        // Get the error count for this shared focus tree
        val errorCount = focusTreeErrors
          .find(_.focusTreeId == s"[Shared Focuses] ${pseudoTree.id.str}")
          .map(_.focusErrors.map(_.errors.size).sum)
          .getOrElse(0)
        // Create error icon pane
        val errorIcon = new ErrorIconPane(
          iconSize = 24,
          errorNumberCount = errorCount,
          onDoubleClick = Some(() => {
            // TODO: Open error details dialog or navigate to error list
            logger.info(s"Double-clicked error icon for shared focuses ${pseudoTree.id.str}")
          }),
          tooltipText = Some(s"$errorCount error(s) in this shared focus file")
        )
        errorIcon.build()
        hbox.getChildren.add(errorIcon)
        vbox.getChildren.add(hbox)
      else
        vbox.getChildren.add(toggleButton)
    )

  @FXML def handleSaveButtonAction(): Unit = {
    ZIO.serviceWithZIO[LocalizationService] { service =>
      service.saveLocalization()
    }
  }

  /**
   * takes the focuses in the focustree and list them in the table
   * @param someFocusTree
   */
  def loadFocusTree(someFocusTree: FocusTree): Unit =
    // Set up cell value factories for each column if not already set
    if focusIDColumn.getCellValueFactory == null then
      setupTableColumns()
      setupCellFactories()
      setupRowFactory()

    // Create an observable list from the focuses
    val focusList: ObservableList[Focus] = FXCollections.observableArrayList()
    someFocusTree.listFocuses.foreach(focus => focusList.add(focus))

    // Set the items in the table
    focusListTable.setItems(focusList)

    // Update the progress indicator based on localization completeness
    updateProgressIndicator(focusList)

  /**
   * Sets up the cell value factories for all table columns
   */
  private def setupTableColumns(): Unit =
    // ID Column - not editable
    focusIDColumn.setCellValueFactory(cellData => {
      new javafx.beans.property.SimpleStringProperty(
        cellData.getValue.id.value.getOrElse("")
      )
    })

    // Name Column - editable
    focusNameColumn.setCellValueFactory(cellData => {
      new javafx.beans.property.SimpleStringProperty(
        zio.Unsafe.unsafe { implicit unsafe =>
          HOIIVUtils.getActiveRuntime.unsafe.run(
            ZIO.serviceWithZIO[LocalizationService](_.getLocalization(cellData.getValue.id.str))
              .map(_.fold("")(_.text))
          ).getOrThrow()
        }
      )
    })

    // Description Column - editable
    focusDescColumn.setCellValueFactory(cellData => {
      new javafx.beans.property.SimpleStringProperty(
        zio.Unsafe.unsafe { implicit unsafe =>
          HOIIVUtils.getActiveRuntime.unsafe.run(
            ZIO.serviceWithZIO[LocalizationService](_.getLocalization(cellData.getValue.id.str + "_desc"))
              .map(_.fold("")(_.text))
          ).getOrThrow()
        }
      )
    })

    // Localization Status Column
    focusLocStatusColumn.setCellValueFactory(cellData => {
      val focus = cellData.getValue
      val nameStatus = focus.localizationStatus(Property.NAME)
      val descStatus = focus.localizationStatus(Property.DESCRIPTION)

      val statusText = s"Name: $nameStatus, Desc: $descStatus"
      new javafx.beans.property.SimpleStringProperty(statusText)
    })

  /**
   * Sets up the cell factories to make columns editable
   */
  private def setupCellFactories(): Unit =
    // Make name and description columns editable
    focusNameColumn.setCellFactory(TextFieldTableCell.forTableColumn())
    focusDescColumn.setCellFactory(TextFieldTableCell.forTableColumn())
    focusLocStatusColumn.setCellFactory(TextFieldTableCell.forTableColumn())

    // Set up edit commit handlers
    focusNameColumn.setOnEditCommit(event => {
      val focus = event.getRowValue
      focus.replaceName(event.getNewValue)
      focusListTable.refresh() // Force update of the table view
    })

    focusDescColumn.setOnEditCommit(event => {
      val focus = event.getRowValue
      focus.replaceLocalization(Property.DESCRIPTION, event.getNewValue)
      focusListTable.refresh() // Force update of the table view
    })

  /**
   * Sets up the row factory to color-code rows based on localization status
   */
  private def setupRowFactory(): Unit =
    focusListTable.setRowFactory(_ => new TableRow[Focus]() {
      override protected def updateItem(focus: Focus, empty: Boolean): Unit = {
        super.updateItem(focus, empty)

        if (focus == null || empty) {
          setGraphic(null)
          setStyle("")
        } else {
          val nameStatus = focus.localizationStatus(Property.NAME)
          val descStatus = focus.localizationStatus(Property.DESCRIPTION)

          val hasUpdated = nameStatus == Localization.Status.UPDATED ||
            descStatus == Localization.Status.UPDATED
          val hasNew = nameStatus == Localization.Status.NEW ||
            descStatus == Localization.Status.NEW

          if (hasUpdated || hasNew) {
            setTextFill(Color.BLACK)
            setStyle("-fx-font-weight: bold; -fx-background-color: #328fa8;")
          } else {
            setTextFill(Color.BLACK)
            setStyle("-fx-background-color: transparent;")
          }
        }
      }
    })

  /**
   * Updates the progress indicator based on localization completeness
   */
  private def updateProgressIndicator(focusList: ObservableList[Focus]): Unit =
    val totalFocuses = focusList.size()
    if totalFocuses > 0 then
      val localizedCount = focusList.stream()
        .filter(focus => {
//          ZIO.serviceWithZIO[LocalizationService] { service =>
//            ZIO.foreach(keys)(service.getLocalizationFile)
//              .map(_.find(_ != null))
//          }
//          ZIO.serviceWithZIO[LocalizationService] { service =>
//            val hasName = service.getLocalization(focus.id.str).map(_.isDefined)
//            val hasDesc = service.getLocalization(focus.id.str + "_desc").map(_.isDefined)
//            hasName && hasDesc
//          }
//          for { 
//            service <- ZIO.service[LocalizationService]
//            hasName <- service.isLocalized(focus.id.str)
//            hasDesc <- service.isLocalized(focus.id.str + "_desc")
//          } yield hasName && hasDesc
          zio.Unsafe.unsafe { implicit unsafe =>
            HOIIVUtils.getActiveRuntime.unsafe.run(
              for {
                service <- ZIO.service[LocalizationService]
                hasName <- service.isLocalized(focus.id.str)
                hasDesc <- service.isLocalized(focus.id.str + "_desc")
              } yield hasName && hasDesc
            ).getOrThrow()
          }
        })
        .count()

      val progress = localizedCount.toDouble / totalFocuses.toDouble
      progressIndicator.setProgress(progress)
    else
      progressIndicator.setProgress(0.0)
