module main.java.com.HOIIVUtils {
    requires transitive javafx.controls;
    requires javafx.fxml;
    requires static lombok;
    requires org.apache.logging.log4j;
    requires java.sql;
    requires java.desktop;
    requires org.jetbrains.annotations;
    requires org.jgrapht.core;
    requires org.apache.poi.poi;
    requires aparapi; // leave aparapi last cause aparapi has terrible config
    requires org.xerial.sqlitejdbc;
    requires io.github.javadiffutils;
    requires org.fxmisc.richtext;
    requires reactfx;
    requires kotlin.stdlib;

    opens main.java.com.hoi4utils.ui to javafx.fxml;
    opens main.java.com.hoi4utils.ui.buildings to javafx.fxml;
    opens main.java.com.hoi4utils.ui.clausewitz_gfx to javafx.fxml;
    opens main.java.com.hoi4utils.ui.colorgen to javafx.fxml;
    opens main.java.com.hoi4utils.ui.console to javafx.fxml;
    opens main.java.com.hoi4utils.ui.focus_view to javafx.fxml;
    opens main.java.com.hoi4utils.ui.hoi4localization to javafx.fxml;
    opens main.java.com.hoi4utils.ui.javafx.export to javafx.fxml;
    opens main.java.com.hoi4utils.ui.javafx.image to javafx.fxml;
    opens main.java.com.hoi4utils.ui.javafx.table to javafx.fxml;
    opens main.java.com.hoi4utils.ui.map to javafx.fxml;
    opens main.java.com.hoi4utils.ui.menu to javafx.fxml;
    opens main.java.com.hoi4utils.ui.message to javafx.fxml;
    opens main.java.com.hoi4utils.ui.parser to javafx.fxml;
    opens main.java.com.hoi4utils.ui.settings to javafx.fxml;
    opens main.java.com.hoi4utils.ui.statistics to javafx.fxml;
    opens main.java.com.hoi4utils.ui.units to javafx.fxml;

    // Export other necessary packages (adjust if needed)
    exports main.java.com.hoi4utils.clausewitz_parser;
    exports main.java.com.hoi4utils.clauzewitz;
    exports main.java.com.hoi4utils.clauzewitz.code;
    exports main.java.com.hoi4utils.clauzewitz.code.defines;
    exports main.java.com.hoi4utils.clauzewitz.code.effect;
    exports main.java.com.hoi4utils.clauzewitz.code.modifier;
    exports main.java.com.hoi4utils.clauzewitz.code.scope;
    //exports main.java.com.HOIIVUtils.hoi4utils.clausewitz_code.trigger;
    exports main.java.com.hoi4utils.clauzewitz.data.country;
    exports main.java.com.hoi4utils.clauzewitz.data.focus;
    exports main.java.com.hoi4utils.clauzewitz.data.gfx;
    exports main.java.com.hoi4utils.clauzewitz.data.idea;
    exports main.java.com.hoi4utils.clauzewitz.localization;
    exports main.java.com.hoi4utils.clauzewitz.data.province;
    exports main.java.com.hoi4utils.clauzewitz.data.technology;
    exports main.java.com.hoi4utils.clauzewitz.data.tooltip;
    exports main.java.com.hoi4utils.clauzewitz.data.units;
    exports main.java.com.hoi4utils.clauzewitz.map;
    exports main.java.com.hoi4utils.clauzewitz.map.buildings;
    exports main.java.com.hoi4utils.clauzewitz.map.gen;
    exports main.java.com.hoi4utils.clauzewitz.map.province;
    exports main.java.com.hoi4utils.clauzewitz.map.resources;
    exports main.java.com.hoi4utils.clauzewitz.map.seed;
    exports main.java.com.hoi4utils.clauzewitz.map.state;
    exports main.java.com.hoi4utils.clauzewitz.map.test;
    exports main.java.com.hoi4utils.ui;
    exports main.java.com.hoi4utils.ui.buildings;
    exports main.java.com.hoi4utils.ui.clausewitz_gfx;
    exports main.java.com.hoi4utils.ui.colorgen;
    exports main.java.com.hoi4utils.ui.console;
    exports main.java.com.hoi4utils.ui.focus_view;
    exports main.java.com.hoi4utils.ui.hoi4localization;
    exports main.java.com.hoi4utils.ui.javafx.export;
    exports main.java.com.hoi4utils.ui.javafx.image;
    exports main.java.com.hoi4utils.ui.javafx.table;
    exports main.java.com.hoi4utils.ui.map;
    exports main.java.com.hoi4utils.ui.menu;
    exports main.java.com.hoi4utils.ui.message;
    exports main.java.com.hoi4utils.ui.parser;
    exports main.java.com.hoi4utils.ui.settings;
    exports main.java.com.hoi4utils.ui.statistics;
    exports main.java.com.hoi4utils.ui.units;
    exports main.java.com.hoi4utils;
    exports main.java.com.hoi4utils.clauzewitz.script;
}