package com.hoi4utils.clausewitz.script

import java.io.{File, FileNotFoundException, PrintWriter}
import scala.util.Using
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Logger

import java.time.LocalDateTime
import javax.swing.JOptionPane

trait PDXFile extends PDXScript[?] {
  def getFile: Option[File]
  
  def fileName: String = getFile match {
    case Some(file) => file.getName
    case None => getClass.getSimpleName + ".txt"
  }

  def save(): Unit = {
    this.getFile match {
      case Some(file) =>
        Using(new PrintWriter(file)) { writer =>
          writer.println(s"### Generated by HOI4Utils, time: ${LocalDateTime.now} ###")
          writer.println(this.toScript)
          LOGGER.info("Exported PDXScript {} to {}", this, file)
        } recover {
          case e: FileNotFoundException =>
            LOGGER.error("Error exporting PDXScript: {}", e.getMessage)
            JOptionPane.showMessageDialog(null, "Error exporting PDXScript: " + e.getMessage, "Error", JOptionPane.ERROR_MESSAGE)
        }
      case None =>
        LOGGER.error("Error exporting PDXScript: No file found for {}", this)
        JOptionPane.showMessageDialog(null, s"Error exporting PDXScript: No file found for $this", "Error", JOptionPane.ERROR_MESSAGE)
    }
  }

}
