; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "HOIIVUtils"
#define MyAppVersion "9.0.0"

[Setup]
SignTool=signtool12
Uninstallable=yes
AppName={#MyAppName}
AppVersion={#MyAppVersion}
OutputDir=C:\Program Files\HOIIVUtils
OutputBaseFilename=HOIIVUtils
Compression=lzma
SolidCompression=yes

[Files]
Source: "HOIIVUtils.EXE"; DestDir: "{app}"